<?php

$versions = array(
  '4.x' => array(
    '4.0.0' => array(
      'name'      => '4.0.0',
      'timestamp' => 1110222639,
    ),
    '4.1.0' => array(
      'name'      => '4.1.0',
      'timestamp' => 1110222639,
    ),
    '4.2.0' => array(
      'name'      => '4.2.0',
      'timestamp' => 1110222639,
    ),
    '4.3.0' => array(
      'name'      => '4.3.0',
      'timestamp' => 1110222639,
    ),
    '4.3.1' => array(
      'name'      => '4.3.1',
      'timestamp' => 1110222639,
    ),
    '4.3.2' => array(
      'name'      => '4.3.2',
      'timestamp' => 1110222639,
    ),
    '4.4.0' => array(
      'name'      => '4.4.0',
      'timestamp' => 1110222639,
    ),
    '4.4.1' => array(
      'name'      => '4.4.1',
      'timestamp' => 1110222639,
    ),
    '4.4.2' => array(
      'name'      => '4.4.2',
      'timestamp' => 1110222639,
    ),
    '4.4.3' => array(
      'name'      => '4.4.3',
      'timestamp' => 1117663917,
    ),
    '4.5.0' => array(
      'name'      => '4.5.0',
      'timestamp' => 1110222639,
    ),
    '4.5.1' => array(
      'name'      => '4.5.1',
      'timestamp' => 1110222639,
    ),
    '4.5.2' => array(
      'name'      => '4.5.2',
      'timestamp' => 1110222639,
    ),
    '4.5.3' => array(
      'name'      => '4.5.3',
      'timestamp' => 1117663886,
    ),
    '4.5.4' => array(
      'name'      => '4.5.4',
      'timestamp' => 1120089035,
    ),
    '4.5.5' => array(
      'name'      => '4.5.5',
      'timestamp' => 1124067343,
    ),
    '4.5.6' => array(
      'name'      => '4.5.6',
      'timestamp' => 1133428161,
    ),
    '4.5.7' => array(
      'name'      => '4.5.7',
      'timestamp' => 1134415223,
    ),
    '4.5.8' => array(
      'name'      => '4.5.8',
      'timestamp' => 1142297923,
    ),
    '4.6.0' => array(
      'name'      => '4.6.0',
      'timestamp' => 1113584559,
    ),
    '4.6.1' => array(
      'name'      => '4.6.1',
      'timestamp' => 1117663993,
    ),
    '4.6.10' => array(
      'name'      => '4.6.10',
      'timestamp' => 1161204172,
    ),
    '4.6.11' => array(
      'name'      => '4.6.11',
      'timestamp' => 1167958043,
    ),
    '4.6.2' => array(
      'name'      => '4.6.2',
      'timestamp' => 1120091000,
    ),
    '4.6.3' => array(
      'name'      => '4.6.3',
      'timestamp' => 1124067344,
    ),
    '4.6.4' => array(
      'name'      => '4.6.4',
      'timestamp' => 1133428375,
    ),
    '4.6.5' => array(
      'name'      => '4.6.5',
      'timestamp' => 1134415225,
    ),
    '4.6.6' => array(
      'name'      => '4.6.6',
      'timestamp' => 1142297928,
    ),
    '4.6.7' => array(
      'name'      => '4.6.7',
      'timestamp' => 1148521162,
    ),
    '4.6.8' => array(
      'name'      => '4.6.8',
      'timestamp' => 1149207025,
    ),
    '4.6.9' => array(
      'name'      => '4.6.9',
      'timestamp' => 1154543063,
    ),
    '4.6.x-dev' => array(
      'name'      => '4.6.x-dev',
      'timestamp' => 1428293071,
    ),
    '4.7.0' => array(
      'name'      => '4.7.0',
      'timestamp' => 1146477046,
    ),
    '4.7.0-beta3' => array(
      'name'      => '4.7.0-beta3',
      'timestamp' => 1136848840,
    ),
    '4.7.0-beta4' => array(
      'name'      => '4.7.0-beta4',
      'timestamp' => 1138307049,
    ),
    '4.7.0-beta5' => array(
      'name'      => '4.7.0-beta5',
      'timestamp' => 1141335933,
    ),
    '4.7.0-beta6' => array(
      'name'      => '4.7.0-beta6',
      'timestamp' => 1142297926,
    ),
    '4.7.0-rc1' => array(
      'name'      => '4.7.0-rc1',
      'timestamp' => 1143798968,
    ),
    '4.7.0-rc2' => array(
      'name'      => '4.7.0-rc2',
      'timestamp' => 1144429093,
    ),
    '4.7.0-rc3' => array(
      'name'      => '4.7.0-rc3',
      'timestamp' => 1145075079,
    ),
    '4.7.0-rc4' => array(
      'name'      => '4.7.0-rc4',
      'timestamp' => 1146232878,
    ),
    '4.7.1' => array(
      'name'      => '4.7.1',
      'timestamp' => 1148521146,
    ),
    '4.7.10' => array(
      'name'      => '4.7.10',
      'timestamp' => 1196972986,
    ),
    '4.7.11' => array(
      'name'      => '4.7.11',
      'timestamp' => 1200003924,
    ),
    '4.7.2' => array(
      'name'      => '4.7.2',
      'timestamp' => 1149207013,
    ),
    '4.7.3' => array(
      'name'      => '4.7.3',
      'timestamp' => 1154543065,
    ),
    '4.7.4' => array(
      'name'      => '4.7.4',
      'timestamp' => 1161204179,
    ),
    '4.7.5' => array(
      'name'      => '4.7.5',
      'timestamp' => 1167958116,
    ),
    '4.7.6' => array(
      'name'      => '4.7.6',
      'timestamp' => 1170107654,
    ),
    '4.7.7' => array(
      'name'      => '4.7.7',
      'timestamp' => 1185477938,
    ),
    '4.7.8' => array(
      'name'      => '4.7.8',
      'timestamp' => 1192657356,
    ),
    '4.7.9' => array(
      'name'      => '4.7.9',
      'timestamp' => 1196889351,
    ),
    '4.7.x-dev' => array(
      'name'      => '4.7.x-dev',
      'timestamp' => 1428293071,
    ),
  ),
  '5.x' => array(
    '5.0' => array(
      'name'      => '5.0',
      'timestamp' => 1168863377,
    ),
    '5.0-beta1' => array(
      'name'      => '5.0-beta1',
      'timestamp' => 1162307974,
    ),
    '5.0-beta2' => array(
      'name'      => '5.0-beta2',
      'timestamp' => 1164731781,
    ),
    '5.0-rc1' => array(
      'name'      => '5.0-rc1',
      'timestamp' => 1166174381,
    ),
    '5.0-rc2' => array(
      'name'      => '5.0-rc2',
      'timestamp' => 1168457781,
    ),
    '5.1' => array(
      'name'      => '5.1',
      'timestamp' => 1170116375,
    ),
    '5.10' => array(
      'name'      => '5.10',
      'timestamp' => 1218672271,
    ),
    '5.11' => array(
      'name'      => '5.11',
      'timestamp' => 1223496711,
    ),
    '5.12' => array(
      'name'      => '5.12',
      'timestamp' => 1224703581,
    ),
    '5.13' => array(
      'name'      => '5.13',
      'timestamp' => 1228948853,
    ),
    '5.14' => array(
      'name'      => '5.14',
      'timestamp' => 1229017408,
    ),
    '5.15' => array(
      'name'      => '5.15',
      'timestamp' => 1231976017,
    ),
    '5.16' => array(
      'name'      => '5.16',
      'timestamp' => 1235603915,
    ),
    '5.17' => array(
      'name'      => '5.17',
      'timestamp' => 1241050627,
    ),
    '5.18' => array(
      'name'      => '5.18',
      'timestamp' => 1242244726,
    ),
    '5.19' => array(
      'name'      => '5.19',
      'timestamp' => 1246481811,
    ),
    '5.2' => array(
      'name'      => '5.2',
      'timestamp' => 1185477847,
    ),
    '5.20' => array(
      'name'      => '5.20',
      'timestamp' => 1253129998,
    ),
    '5.21' => array(
      'name'      => '5.21',
      'timestamp' => 1260996565,
    ),
    '5.22' => array(
      'name'      => '5.22',
      'timestamp' => 1267661987,
    ),
    '5.23' => array(
      'name'      => '5.23',
      'timestamp' => 1281559317,
    ),
    '5.3' => array(
      'name'      => '5.3',
      'timestamp' => 1192656827,
    ),
    '5.4' => array(
      'name'      => '5.4',
      'timestamp' => 1196889555,
    ),
    '5.5' => array(
      'name'      => '5.5',
      'timestamp' => 1196972817,
    ),
    '5.6' => array(
      'name'      => '5.6',
      'timestamp' => 1200003563,
    ),
    '5.7' => array(
      'name'      => '5.7',
      'timestamp' => 1201565148,
    ),
    '5.8' => array(
      'name'      => '5.8',
      'timestamp' => 1215640562,
    ),
    '5.9' => array(
      'name'      => '5.9',
      'timestamp' => 1216843154,
    ),
    '5.x-dev' => array(
      'name'      => '5.x-dev',
      'timestamp' => 1428293071,
    ),
  ),
  '6.x' => array(
    '6.0' => array(
      'name'      => '6.0',
      'timestamp' => 1202912942,
    ),
    '6.0-beta1' => array(
      'name'      => '6.0-beta1',
      'timestamp' => 1189840539,
    ),
    '6.0-beta2' => array(
      'name'      => '6.0-beta2',
      'timestamp' => 1192657969,
    ),
    '6.0-beta3' => array(
      'name'      => '6.0-beta3',
      'timestamp' => 1195684565,
    ),
    '6.0-beta4' => array(
      'name'      => '6.0-beta4',
      'timestamp' => 1196889685,
    ),
    '6.0-rc1' => array(
      'name'      => '6.0-rc1',
      'timestamp' => 1198191023,
    ),
    '6.0-rc2' => array(
      'name'      => '6.0-rc2',
      'timestamp' => 1200005572,
    ),
    '6.0-rc3' => array(
      'name'      => '6.0-rc3',
      'timestamp' => 1201733315,
    ),
    '6.0-rc4' => array(
      'name'      => '6.0-rc4',
      'timestamp' => 1202511824,
    ),
    '6.1' => array(
      'name'      => '6.1',
      'timestamp' => 1204141889,
    ),
    '6.10' => array(
      'name'      => '6.10',
      'timestamp' => 1235595930,
    ),
    '6.11' => array(
      'name'      => '6.11',
      'timestamp' => 1241050669,
    ),
    '6.12' => array(
      'name'      => '6.12',
      'timestamp' => 1242243867,
    ),
    '6.13' => array(
      'name'      => '6.13',
      'timestamp' => 1246481660,
    ),
    '6.14' => array(
      'name'      => '6.14',
      'timestamp' => 1253129845,
    ),
    '6.15' => array(
      'name'      => '6.15',
      'timestamp' => 1260996665,
    ),
    '6.16' => array(
      'name'      => '6.16',
      'timestamp' => 1267661867,
    ),
    '6.17' => array(
      'name'      => '6.17',
      'timestamp' => 1275504976,
    ),
    '6.18' => array(
      'name'      => '6.18',
      'timestamp' => 1281558378,
    ),
    '6.19' => array(
      'name'      => '6.19',
      'timestamp' => 1281559192,
    ),
    '6.2' => array(
      'name'      => '6.2',
      'timestamp' => 1207775758,
    ),
    '6.20' => array(
      'name'      => '6.20',
      'timestamp' => 1292447733,
    ),
    '6.21' => array(
      'name'      => '6.21',
      'timestamp' => 1306354688,
    ),
    '6.22' => array(
      'name'      => '6.22',
      'timestamp' => 1306356876,
    ),
    '6.23' => array(
      'name'      => '6.23',
      'timestamp' => 1328134003,
    ),
    '6.24' => array(
      'name'      => '6.24',
      'timestamp' => 1328134197,
    ),
    '6.25' => array(
      'name'      => '6.25',
      'timestamp' => 1330534350,
    ),
    '6.26' => array(
      'name'      => '6.26',
      'timestamp' => 1335976917,
    ),
    '6.27' => array(
      'name'      => '6.27',
      'timestamp' => 1355943298,
    ),
    '6.28' => array(
      'name'      => '6.28',
      'timestamp' => 1358370669,
    ),
    '6.29' => array(
      'name'      => '6.29',
      'timestamp' => 1384980939,
    ),
    '6.3' => array(
      'name'      => '6.3',
      'timestamp' => 1215640418,
    ),
    '6.30' => array(
      'name'      => '6.30',
      'timestamp' => 1389814918,
    ),
    '6.31' => array(
      'name'      => '6.31',
      'timestamp' => 1397685941,
    ),
    '6.32' => array(
      'name'      => '6.32',
      'timestamp' => 1405542867,
    ),
    '6.33' => array(
      'name'      => '6.33',
      'timestamp' => 1407346209,
    ),
    '6.34' => array(
      'name'      => '6.34',
      'timestamp' => 1416428889,
    ),
    '6.35' => array(
      'name'      => '6.35',
      'timestamp' => 1426706752,
    ),
    '6.4' => array(
      'name'      => '6.4',
      'timestamp' => 1218672351,
    ),
    '6.5' => array(
      'name'      => '6.5',
      'timestamp' => 1223496904,
    ),
    '6.6' => array(
      'name'      => '6.6',
      'timestamp' => 1224703633,
    ),
    '6.7' => array(
      'name'      => '6.7',
      'timestamp' => 1228948281,
    ),
    '6.8' => array(
      'name'      => '6.8',
      'timestamp' => 1229018152,
    ),
    '6.9' => array(
      'name'      => '6.9',
      'timestamp' => 1231976120,
    ),
    '6.x-dev' => array(
      'name'      => '6.x-dev',
      'timestamp' => 1428293071,
    ),
  ),
  '7.x' => array(
    '7.0' => array(
      'name'      => '7.0',
      'timestamp' => 1294208481,
    ),
    '7.0-alpha1' => array(
      'name'      => '7.0-alpha1',
      'timestamp' => 1263566471,
    ),
    '7.0-alpha2' => array(
      'name'      => '7.0-alpha2',
      'timestamp' => 1266777677,
    ),
    '7.0-alpha3' => array(
      'name'      => '7.0-alpha3',
      'timestamp' => 1269192071,
    ),
    '7.0-alpha4' => array(
      'name'      => '7.0-alpha4',
      'timestamp' => 1272317787,
    ),
    '7.0-alpha5' => array(
      'name'      => '7.0-alpha5',
      'timestamp' => 1274628511,
    ),
    '7.0-alpha6' => array(
      'name'      => '7.0-alpha6',
      'timestamp' => 1278634760,
    ),
    '7.0-alpha7' => array(
      'name'      => '7.0-alpha7',
      'timestamp' => 1284599497,
    ),
    '7.0-beta1' => array(
      'name'      => '7.0-beta1',
      'timestamp' => 1286422563,
    ),
    '7.0-beta2' => array(
      'name'      => '7.0-beta2',
      'timestamp' => 1287812047,
    ),
    '7.0-beta3' => array(
      'name'      => '7.0-beta3',
      'timestamp' => 1289694464,
    ),
    '7.0-rc1' => array(
      'name'      => '7.0-rc1',
      'timestamp' => 1291190127,
    ),
    '7.0-rc2' => array(
      'name'      => '7.0-rc2',
      'timestamp' => 1292101584,
    ),
    '7.0-rc3' => array(
      'name'      => '7.0-rc3',
      'timestamp' => 1293099405,
    ),
    '7.0-rc4' => array(
      'name'      => '7.0-rc4',
      'timestamp' => 1293683893,
    ),
    '7.1' => array(
      'name'      => '7.1',
      'timestamp' => 1306354716,
    ),
    '7.10' => array(
      'name'      => '7.10',
      'timestamp' => 1323125284,
    ),
    '7.11' => array(
      'name'      => '7.11',
      'timestamp' => 1328134189,
    ),
    '7.12' => array(
      'name'      => '7.12',
      'timestamp' => 1328134504,
    ),
    '7.13' => array(
      'name'      => '7.13',
      'timestamp' => 1335997138,
    ),
    '7.14' => array(
      'name'      => '7.14',
      'timestamp' => 1335997436,
    ),
    '7.15' => array(
      'name'      => '7.15',
      'timestamp' => 1343839077,
    ),
    '7.16' => array(
      'name'      => '7.16',
      'timestamp' => 1350508347,
    ),
    '7.17' => array(
      'name'      => '7.17',
      'timestamp' => 1352325188,
    ),
    '7.18' => array(
      'name'      => '7.18',
      'timestamp' => 1355943808,
    ),
    '7.19' => array(
      'name'      => '7.19',
      'timestamp' => 1358374569,
    ),
    '7.20' => array(
      'name'      => '7.20',
      'timestamp' => 1361393536,
    ),
    '7.2' => array(
      'name'      => '7.2',
      'timestamp' => 1306356773,
    ),
    '7.21' => array(
      'name'      => '7.21',
      'timestamp' => 1362615560,
    ),
    '7.22' => array(
      'name'      => '7.22',
      'timestamp' => 1365026996,
    ),
    '7.23' => array(
      'name'      => '7.23',
      'timestamp' => 1375928023,
    ),
    '7.24' => array(
      'name'      => '7.24',
      'timestamp' => 1384983233,
    ),
    '7.25' => array(
      'name'      => '7.25',
      'timestamp' => 1388709297,
    ),
    '7.26' => array(
      'name'      => '7.26',
      'timestamp' => 1389815663,
    ),
    '7.27' => array(
      'name'      => '7.27',
      'timestamp' => 1397686039,
    ),
    '7.28' => array(
      'name'      => '7.28',
      'timestamp' => 1399522506,
    ),
    '7.29' => array(
      'name'      => '7.29',
      'timestamp' => 1405542918,
    ),
    '7.3' => array(
      'name'      => '7.3',
      'timestamp' => 1309397130,
    ),
    '7.30' => array(
      'name'      => '7.30',
      'timestamp' => 1406239615,
    ),
    '7.31' => array(
      'name'      => '7.31',
      'timestamp' => 1407346319,
    ),
    '7.32' => array(
      'name'      => '7.32',
      'timestamp' => 1413387291,
    ),
    '7.33' => array(
      'name'      => '7.33',
      'timestamp' => 1415374486,
    ),
    '7.34' => array(
      'name'      => '7.34',
      'timestamp' => 1416428939,
    ),
    '7.35' => array(
      'name'      => '7.35',
      'timestamp' => 1426706825,
    ),
    '7.36' => array(
      'name'      => '7.36',
      'timestamp' => 1427943278,
    ),
    '7.4' => array(
      'name'      => '7.4',
      'timestamp' => 1309397448,
    ),
    '7.5' => array(
      'name'      => '7.5',
      'timestamp' => 1311798258,
    ),
    '7.6' => array(
      'name'      => '7.6',
      'timestamp' => 1311798575,
    ),
    '7.7' => array(
      'name'      => '7.7',
      'timestamp' => 1311813047,
    ),
    '7.8' => array(
      'name'      => '7.8',
      'timestamp' => 1314817475,
    ),
    '7.9' => array(
      'name'      => '7.9',
      'timestamp' => 1319660445,
    ),
    '7.x-dev' => array(
      'name'      => '7.x-dev',
      'timestamp' => 1428293071,
    ),
  ),
  '8.x' => array(
    '8.0-alpha10' => array(
      'name'      => '8.0-alpha10',
      'timestamp' => 1395231484,
    ),
    '8.0-alpha11' => array(
      'name'      => '8.0-alpha11',
      'timestamp' => 1398249029,
    ),
    '8.0-alpha12' => array(
      'name'      => '8.0-alpha12',
      'timestamp' => 1401275955,
    ),
    '8.0-alpha13' => array(
      'name'      => '8.0-alpha13',
      'timestamp' => 1404296508,
    ),
    '8.0-alpha2' => array(
      'name'      => '8.0-alpha2',
      'timestamp' => 1372069443,
    ),
    '8.0-alpha3' => array(
      'name'      => '8.0-alpha3',
      'timestamp' => 1378303239,
    ),
    '8.0-alpha4' => array(
      'name'      => '8.0-alpha4',
      'timestamp' => 1382092168,
    ),
    '8.0-alpha5' => array(
      'name'      => '8.0-alpha5',
      'timestamp' => 1384850056,
    ),
    '8.0-alpha6' => array(
      'name'      => '8.0-alpha6',
      'timestamp' => 1385153041,
    ),
    '8.0-alpha7' => array(
      'name'      => '8.0-alpha7',
      'timestamp' => 1387399663,
    ),
    '8.0-alpha8' => array(
      'name'      => '8.0-alpha8',
      'timestamp' => 1390392894,
    ),
    '8.0-alpha9' => array(
      'name'      => '8.0-alpha9',
      'timestamp' => 1392805782,
    ),
    '8.0.0-alpha14' => array(
      'name'      => '8.0.0-alpha14',
      'timestamp' => 1407344603,
    ),
    '8.0.0-alpha15' => array(
      'name'      => '8.0.0-alpha15',
      'timestamp' => 1411139455,
    ),
    '8.0.0-beta1' => array(
      'name'      => '8.0.0-beta1',
      'timestamp' => 1412147001,
    ),
    '8.0.0-beta2' => array(
      'name'      => '8.0.0-beta2',
      'timestamp' => 1413392637,
    ),
    '8.0.0-beta3' => array(
      'name'      => '8.0.0-beta3',
      'timestamp' => 1415797276,
    ),
    '8.0.0-beta4' => array(
      'name'      => '8.0.0-beta4',
      'timestamp' => 1418825225,
    ),
    '8.0.0-beta6' => array(
      'name'      => '8.0.0-beta6',
      'timestamp' => 1422443458,
    ),
    '8.0.0-beta7' => array(
      'name'      => '8.0.0-beta7',
      'timestamp' => 1424875103,
    ),
    '8.0.0-beta9' => array(
      'name'      => '8.0.0-beta9',
      'timestamp' => 1427300136,
    ),
    '8.0.x-dev' => array(
      'name'      => '8.0.x-dev',
      'timestamp' => 1428293071,
    ),
    '8.1.x-dev' => array(
      'name'      => '8.1.x-dev',
      'timestamp' => 1428293071,
    ),
  ),
  '9.x' => array(
    '9.x-dev' => array(
      'name'      => '9.x-dev',
      'timestamp' => 1428293071,
    ),
  ),
);
