<?php

$versions = array (
  'start' => array(
    'name'      => 'start',
    'timestamp' => 958679520,
  ),
  '3.x' => array(
    '3.0.0' => array(
      'name'      => '3.0.0',
      'timestamp' => 1008929274,
    ),
  ),
  '4.x' => array(
    '4.0.0' => array(
      'name'      => '4.0.0',
      'timestamp' => 1039335614,
    ),
    '4.1.0' => array(
      'name'      => '4.1.0',
      'timestamp' => 1056555870,
    ),
    '4.2.0' => array(
      'name'      => '4.2.0',
      'timestamp' => 1065285950,
    ),
    '4.3.0' => array(
      'name'      => '4.3.0',
      'timestamp' => 1067725408,
    ),
    '4.3.1' => array(
      'name'      => '4.3.1',
      'timestamp' => 1070389386,
    ),
    '4.3.2' => array(
      'name'      => '4.3.2',
      'timestamp' => 1072956210,
    ),
    '4.4.0' => array(
      'name'      => '4.4.0',
      'timestamp' => 1080811307,
    ),
    '4.4.1' => array(
      'name'      => '4.4.1',
      'timestamp' => 1083404762,
    ),
    '4.4.2' => array(
      'name'      => '4.4.2',
      'timestamp' => 1088917575,
    ),
    '4.4.3' => array(
      'name'      => '4.4.3',
      'timestamp' => 1117653662,
    ),
    '4.5.0' => array(
      'name'      => '4.5.0',
      'timestamp' => 1098130436,
    ),
    '4.5.1' => array(
      'name'      => '4.5.1',
      'timestamp' => 1101902996,
    ),
    '4.5.2' => array(
      'name'      => '4.5.2',
      'timestamp' => 1105780141,
    ),
    '4.5.3' => array(
      'name'      => '4.5.3',
      'timestamp' => 1117654032,
    ),
    '4.5.4' => array(
      'name'      => '4.5.4',
      'timestamp' => 1120076593,
    ),
    '4.5.5' => array(
      'name'      => '4.5.5',
      'timestamp' => 1124070121,
    ),
    '4.5.6' => array(
      'name'      => '4.5.6',
      'timestamp' => 1133428816,
    ),
    '4.5.7' => array(
      'name'      => '4.5.7',
      'timestamp' => 1134407442,
    ),
    '4.5.8' => array(
      'name'      => '4.5.8',
      'timestamp' => 1142299195,
    ),
    '4.6.0' => array(
      'name'      => '4.6.0',
      'timestamp' => 1113579928,
    ),
    '4.6.1' => array(
      'name'      => '4.6.1',
      'timestamp' => 1117656964,
    ),
    '4.6.2' => array(
      'name'      => '4.6.2',
      'timestamp' => 1120076607,
    ),
    '4.6.3' => array(
      'name'      => '4.6.3',
      'timestamp' => 1124066591,
    ),
    '4.6.4' => array(
      'name'      => '4.6.4',
      'timestamp' => 1133417200,
    ),
    '4.6.5' => array(
      'name'      => '4.6.5',
      'timestamp' => 1134407352,
    ),
    '4.6.6' => array(
      'name'      => '4.6.6',
      'timestamp' => 1142286072,
    ),
    '4.6.7' => array(
      'name'      => '4.6.7',
      'timestamp' => 1148520845,
    ),
    '4.6.8' => array(
      'name'      => '4.6.8',
      'timestamp' => 1149206843,
    ),
    '4.6.9' => array(
      'name'      => '4.6.9',
      'timestamp' => 1154542385,
    ),
    '4.6.10' => array(
      'name'      => '4.6.10',
      'timestamp' => 1161202448,
    ),
    '4.6.11' => array(
      'name'      => '4.6.11',
      'timestamp' => 1167956202,
    ),
    '4.7.0-beta-3' => array(
      'name'      => '4.7.0-beta-3',
      'timestamp' => 1136834327,
    ),
    '4.7.0-beta-4' => array(
      'name'      => '4.7.0-beta-4',
      'timestamp' => 1138282985,
    ),
    '4.7.0-beta-5' => array(
      'name'      => '4.7.0-beta-5',
      'timestamp' => 1141327002,
    ),
    '4.7.0-beta-6' => array(
      'name'      => '4.7.0-beta-6',
      'timestamp' => 1142286536,
    ),
    '4.7.0-rc-1' => array(
      'name'      => '4.7.0-rc-1',
      'timestamp' => 1143787427,
    ),
    '4.7.0-rc-2' => array(
      'name'      => '4.7.0-rc-2',
      'timestamp' => 1144676729,
    ),
    '4.7.0-rc-3' => array(
      'name'      => '4.7.0-rc-3',
      'timestamp' => 1145074039,
    ),
    '4.7.0-rc-4' => array(
      'name'      => '4.7.0-rc-4',
      'timestamp' => 1146231467,
    ),
    '4.7.0' => array(
      'name'      => '4.7.0',
      'timestamp' => 1146476066,
    ),
    '4.7.1' => array(
      'name'      => '4.7.1',
      'timestamp' => 1148520860,
    ),
    '4.7.2' => array(
      'name'      => '4.7.2',
      'timestamp' => 1149206798,
    ),
    '4.7.3' => array(
      'name'      => '4.7.3',
      'timestamp' => 1154542407,
    ),
    '4.7.4' => array(
      'name'      => '4.7.4',
      'timestamp' => 1161202482,
    ),
    '4.7.5' => array(
      'name'      => '4.7.5',
      'timestamp' => 1167956548,
    ),
    '4.7.6' => array(
      'name'      => '4.7.6',
      'timestamp' => 1170107300,
    ),
    '4.7.7' => array(
      'name'      => '4.7.7',
      'timestamp' => 1185485122,
    ),
    '4.7.8' => array(
      'name'      => '4.7.8',
      'timestamp' => 1192656942,
    ),
    '4.7.9' => array(
      'name'      => '4.7.9',
      'timestamp' => 1196888973,
    ),
    '4.7.10' => array(
      'name'      => '4.7.10',
      'timestamp' => 1196972414,
    ),
    '4.7.11' => array(
      'name'      => '4.7.11',
      'timestamp' => 1200003499,
    ),
  ),
  '5.x' => array(
    '5.0-beta-1' => array(
      'name'      => '5.0-beta-1',
      'timestamp' => 1162307017,
    ),
    '5.0-beta-2' => array(
      'name'      => '5.0-beta-2',
      'timestamp' => 1164724710,
    ),
    '5.0-rc-1' => array(
      'name'      => '5.0-rc-1',
      'timestamp' => 1166172836,
    ),
    '5.0-rc-2' => array(
      'name'      => '5.0-rc-2',
      'timestamp' => 1168456096,
    ),
    '5.0' => array(
      'name'      => '5.0',
      'timestamp' => 1168863084,
    ),
    '5.1' => array(
      'name'      => '5.1',
      'timestamp' => 1170113799,
    ),
    '5.2' => array(
      'name'      => '5.2',
      'timestamp' => 1185477410,
    ),
    '5.3' => array(
      'name'      => '5.3',
      'timestamp' => 1192656540,
    ),
    '5.4' => array(
      'name'      => '5.4',
      'timestamp' => 1196888994,
    ),
    '5.5' => array(
      'name'      => '5.5',
      'timestamp' => 1196972604,
    ),
    '5.6' => array(
      'name'      => '5.6',
      'timestamp' => 1200003264,
    ),
    '5.7' => array(
      'name'      => '5.7',
      'timestamp' => 1201564844,
    ),
    '5.8' => array(
      'name'      => '5.8',
      'timestamp' => 1215640122,
    ),
    '5.9' => array(
      'name'      => '5.9',
      'timestamp' => 1216842770,
    ),
    '5.10' => array(
      'name'      => '5.10',
      'timestamp' => 1218671949,
    ),
    '5.11' => array(
      'name'      => '5.11',
      'timestamp' => 1223496626,
    ),
    '5.12' => array(
      'name'      => '5.12',
      'timestamp' => 1224703528,
    ),
    '5.13' => array(
      'name'      => '5.13',
      'timestamp' => 1228947687,
    ),
    '5.14' => array(
      'name'      => '5.14',
      'timestamp' => 1229017047,
    ),
    '5.15' => array(
      'name'      => '5.15',
      'timestamp' => 1231975935,
    ),
    '5.16' => array(
      'name'      => '5.16',
      'timestamp' => 1235603645,
    ),
    '5.17' => array(
      'name'      => '5.17',
      'timestamp' => 1241050429,
    ),
    '5.18' => array(
      'name'      => '5.18',
      'timestamp' => 1242244151,
    ),
    '5.19' => array(
      'name'      => '5.19',
      'timestamp' => 1246481531,
    ),
    '5.20' => array(
      'name'      => '5.20',
      'timestamp' => 1253129620,
    ),
    '5.21' => array(
      'name'      => '5.21',
      'timestamp' => 1260996391,
    ),
    '5.22' => array(
      'name'      => '5.22',
      'timestamp' => 1267661762,
    ),
    '5.23' => array(
      'name'      => '5.23',
      'timestamp' => 1281559069,
    ),
  ),
  '6.x' => array(
    '6.0-beta-1' => array(
      'name'      => '6.0-beta-1',
      'timestamp' => 1189800539,
    ),
    '6.0-beta-2' => array(
      'name'      => '6.0-beta-2',
      'timestamp' => 1192657634,
    ),
    '6.0-beta-3' => array(
      'name'      => '6.0-beta-3',
      'timestamp' => 1195684410,
    ),
    '6.0-beta-4' => array(
      'name'      => '6.0-beta-4',
      'timestamp' => 1196889509,
    ),
    '6.0-rc-1' => array(
      'name'      => '6.0-rc-1',
      'timestamp' => 1198190484,
    ),
    '6.0-rc-2' => array(
      'name'      => '6.0-rc-2',
      'timestamp' => 1200005237,
    ),
    '6.0-rc-3' => array(
      'name'      => '6.0-rc-3',
      'timestamp' => 1201733035,
    ),
    '6.0-rc-4' => array(
      'name'      => '6.0-rc-4',
      'timestamp' => 1202511650,
    ),
    '6.0' => array(
      'name'      => '6.0',
      'timestamp' => 1202912742,
    ),
    '6.1' => array(
      'name'      => '6.1',
      'timestamp' => 1204141484,
    ),
    '6.2' => array(
      'name'      => '6.2',
      'timestamp' => 1207775511,
    ),
    '6.3' => array(
      'name'      => '6.3',
      'timestamp' => 1215640108,
    ),
    '6.4' => array(
      'name'      => '6.4',
      'timestamp' => 1218671954,
    ),
    '6.5' => array(
      'name'      => '6.5',
      'timestamp' => 1223496738,
    ),
    '6.6' => array(
      'name'      => '6.6',
      'timestamp' => 1224703562,
    ),
    '6.7' => array(
      'name'      => '6.7',
      'timestamp' => 1228948214,
    ),
    '6.8' => array(
      'name'      => '6.8',
      'timestamp' => 1229017182,
    ),
    '6.9' => array(
      'name'      => '6.9',
      'timestamp' => 1231976048,
    ),
    '6.10' => array(
      'name'      => '6.10',
      'timestamp' => 1235595757,
    ),
    '6.11' => array(
      'name'      => '6.11',
      'timestamp' => 1241050411,
    ),
    '6.12' => array(
      'name'      => '6.12',
      'timestamp' => 1242243513,
    ),
    '6.13' => array(
      'name'      => '6.13',
      'timestamp' => 1246481516,
    ),
    '6.14' => array(
      'name'      => '6.14',
      'timestamp' => 1253129654,
    ),
    '6.15' => array(
      'name'      => '6.15',
      'timestamp' => 1260996430,
    ),
    '6.16' => array(
      'name'      => '6.16',
      'timestamp' => 1267661728,
    ),
    '6.17' => array(
      'name'      => '6.17',
      'timestamp' => 1275504752,
    ),
    '6.18' => array(
      'name'      => '6.18',
      'timestamp' => 1281558147,
    ),
    '6.19' => array(
      'name'      => '6.19',
      'timestamp' => 1281558948,
    ),
    '6.20' => array(
      'name'      => '6.20',
      'timestamp' => 1292447483,
    ),
    '6.21' => array(
      'name'      => '6.21',
      'timestamp' => 1306353768,
    ),
    '6.22' => array(
      'name'      => '6.22',
      'timestamp' => 1306356235,
    ),
    '6.23' => array(
      'name'      => '6.23',
      'timestamp' => 1328131573,
    ),
    '6.24' => array(
      'name'      => '6.24',
      'timestamp' => 1328133324,
    ),
    '6.25' => array(
      'name'      => '6.25',
      'timestamp' => 1330533851,
    ),
    '6.26' => array(
      'name'      => '6.26',
      'timestamp' => 1335976576,
    ),
    '6.27' => array(
      'name'      => '6.27',
      'timestamp' => 1355943103,
    ),
    '6.28' => array(
      'name'      => '6.28',
      'timestamp' => 1358370550,
    ),
    '6.29' => array(
      'name'      => '6.29',
      'timestamp' => 1384979878,
    ),
    '6.30' => array(
      'name'      => '6.30',
      'timestamp' => 1389814548,
    ),
    '6.31' => array(
      'name'      => '6.31',
      'timestamp' => 1397685266,
    ),
    '6.32' => array(
      'name'      => '6.32',
      'timestamp' => 1405542442,
    ),
    '6.33' => array(
      'name'      => '6.33',
      'timestamp' => 1407344854,
    ),
    '6.34' => array(
      'name'      => '6.34',
      'timestamp' => 1416428314,
    ),
    '6.35' => array(
      'name'      => '6.35',
      'timestamp' => 1426706052,
    ),
  ),
  '7.x' => array(
    '7.0-unstable-1' => array(
      'name'      => '7.0-unstable-1',
      'timestamp' => 1222822483,
    ),
    '7.0-unstable-2' => array(
      'name'      => '7.0-unstable-2',
      'timestamp' => 1223838184,
    ),
    '7.0-unstable-3' => array(
      'name'      => '7.0-unstable-3',
      'timestamp' => 1226564036,
    ),
    '7.0-unstable-4' => array(
      'name'      => '7.0-unstable-4',
      'timestamp' => 1231969704,
    ),
    '7.0-unstable-5' => array(
      'name'      => '7.0-unstable-5',
      'timestamp' => 1234675134,
    ),
    '7.0-unstable-6' => array(
      'name'      => '7.0-unstable-6',
      'timestamp' => 1237459731,
    ),
    '7.0-unstable-7' => array(
      'name'      => '7.0-unstable-7',
      'timestamp' => 1243390913,
    ),
    '7.0-unstable-8' => array(
      'name'      => '7.0-unstable-8',
      'timestamp' => 1248387267,
    ),
    '7.0-unstable-9' => array(
      'name'      => '7.0-unstable-9',
      'timestamp' => 1252985887,
    ),
    '7.0-unstable-10' => array(
      'name'      => '7.0-unstable-10',
      'timestamp' => 1257688683,
    ),
    '7.0-alpha1' => array(
      'name'      => '7.0-alpha1',
      'timestamp' => 1263566108,
    ),
    '7.0-alpha2' => array(
      'name'      => '7.0-alpha2',
      'timestamp' => 1266775644,
    ),
    '7.0-alpha3' => array(
      'name'      => '7.0-alpha3',
      'timestamp' => 1269190286,
    ),
    '7.0-alpha4' => array(
      'name'      => '7.0-alpha4',
      'timestamp' => 1272317094,
    ),
    '7.0-alpha5' => array(
      'name'      => '7.0-alpha5',
      'timestamp' => 1274628398,
    ),
    '7.0-alpha6' => array(
      'name'      => '7.0-alpha6',
      'timestamp' => 1278634442,
    ),
    '7.0-alpha7' => array(
      'name'      => '7.0-alpha7',
      'timestamp' => 1284599374,
    ),
    '7.0-beta1' => array(
      'name'      => '7.0-beta1',
      'timestamp' => 1286422379,
    ),
    '7.0-beta2' => array(
      'name'      => '7.0-beta2',
      'timestamp' => 1287811857,
    ),
    '7.0-beta3' => array(
      'name'      => '7.0-beta3',
      'timestamp' => 1289693981,
    ),
    '7.0-beta-3' => array(
      'name'      => '7.0-beta-3',
      'timestamp' => 1288562541,
    ),
    '7.0-rc-1' => array(
      'name'      => '7.0-rc-1',
      'timestamp' => 1291189946,
    ),
    '7.0-rc-2' => array(
      'name'      => '7.0-rc-2',
      'timestamp' => 1292101152,
    ),
    '7.0-rc-3' => array(
      'name'      => '7.0-rc-3',
      'timestamp' => 1293099093,
    ),
    '7.0-rc-4' => array(
      'name'      => '7.0-rc-4',
      'timestamp' => 1293683700,
    ),
    '7.0' => array(
      'name'      => '7.0',
      'timestamp' => 1294208278,
    ),
    '7.1' => array(
      'name'      => '7.1',
      'timestamp' => 1306354033,
    ),
    '7.2' => array(
      'name'      => '7.2',
      'timestamp' => 1306356102,
    ),
    '7.3' => array(
      'name'      => '7.3',
      'timestamp' => 1309396344,
    ),
    '7.4' => array(
      'name'      => '7.4',
      'timestamp' => 1309396810,
    ),
    '7.5' => array(
      'name'      => '7.5',
      'timestamp' => 1311797860,
    ),
    '7.6' => array(
      'name'      => '7.6',
      'timestamp' => 1311797978,
    ),
    '7.7' => array(
      'name'      => '7.7',
      'timestamp' => 1311811344,
    ),
    '7.8' => array(
      'name'      => '7.8',
      'timestamp' => 1314816934,
    ),
    '7.9' => array(
      'name'      => '7.9',
      'timestamp' => 1319658820,
    ),
    '7.10' => array(
      'name'      => '7.10',
      'timestamp' => 1323123535,
    ),
    '7.11' => array(
      'name'      => '7.11',
      'timestamp' => 1328131791,
    ),
    '7.12' => array(
      'name'      => '7.12',
      'timestamp' => 1328133794,
    ),
    '7.13' => array(
      'name'      => '7.13',
      'timestamp' => 1335996091,
    ),
    '7.14' => array(
      'name'      => '7.14',
      'timestamp' => 1335996642,
    ),
    '7.15' => array(
      'name'      => '7.15',
      'timestamp' => 1343838462,
    ),
    '7.16' => array(
      'name'      => '7.16',
      'timestamp' => 1350506704,
    ),
    '7.17' => array(
      'name'      => '7.17',
      'timestamp' => 1352324533,
    ),
    '7.18' => array(
      'name'      => '7.18',
      'timestamp' => 1355943179,
    ),
    '7.19' => array(
      'name'      => '7.19',
      'timestamp' => 1358372748,
    ),
    '7.20' => array(
      'name'      => '7.20',
      'timestamp' => 1361392370,
    ),
    '7.21' => array(
      'name'      => '7.21',
      'timestamp' => 1362614658,
    ),
    '7.22' => array(
      'name'      => '7.22',
      'timestamp' => 1365024592,
    ),
    '7.23' => array(
      'name'      => '7.23',
      'timestamp' => 1375927466,
    ),
    '7.24' => array(
      'name'      => '7.24',
      'timestamp' => 1384980359,
    ),
    '7.25' => array(
      'name'      => '7.25',
      'timestamp' => 1388708926,
    ),
    '7.26' => array(
      'name'      => '7.26',
      'timestamp' => 1389814996,
    ),
    '7.27' => array(
      'name'      => '7.27',
      'timestamp' => 1397684674,
    ),
    '7.28' => array(
      'name'      => '7.28',
      'timestamp' => 1399521900,
    ),
    '7.29' => array(
      'name'      => '7.29',
      'timestamp' => 1405540982,
    ),
    '7.30' => array(
      'name'      => '7.30',
      'timestamp' => 1406239098,
    ),
    '7.31' => array(
      'name'      => '7.31',
      'timestamp' => 1407345243,
    ),
    '7.32' => array(
      'name'      => '7.32',
      'timestamp' => 1413383806,
    ),
    '7.33' => array(
      'name'      => '7.33',
      'timestamp' => 1415373927,
    ),
    '7.34' => array(
      'name'      => '7.34',
      'timestamp' => 1416428669,
    ),
    '7.35' => array(
      'name'      => '7.35',
      'timestamp' => 1426706437,
    ),
    '7.36' => array(
      'name'      => '7.36',
      'timestamp' => 1427942954,
    ),
  ),
  '8.x' => array(
    '8.0-alpha1' => array(
      'name'      => '8.0-alpha1',
      'timestamp' => 1369015412,
    ),
    '8.0-alpha2' => array(
      'name'      => '8.0-alpha2',
      'timestamp' => 1372068523,
    ),
    '8.0-alpha3' => array(
      'name'      => '8.0-alpha3',
      'timestamp' => 1378292959,
    ),
    '8.0-alpha4' => array(
      'name'      => '8.0-alpha4',
      'timestamp' => 1382086496,
    ),
    '8.0-alpha5' => array(
      'name'      => '8.0-alpha5',
      'timestamp' => 1384823700,
    ),
    '8.0-alpha6' => array(
      'name'      => '8.0-alpha6',
      'timestamp' => 1385128610,
    ),
    '8.0-alpha7' => array(
      'name'      => '8.0-alpha7',
      'timestamp' => 1387398156,
    ),
    '8.0-alpha8' => array(
      'name'      => '8.0-alpha8',
      'timestamp' => 1390380613,
    ),
    '8.0-alpha9' => array(
      'name'      => '8.0-alpha9',
      'timestamp' => 1392764759,
    ),
    '8.0-alpha10' => array(
      'name'      => '8.0-alpha10',
      'timestamp' => 1395137853,
    ),
    '8.0-alpha11' => array(
      'name'      => '8.0-alpha11',
      'timestamp' => 1398244216,
    ),
    '8.0-alpha12' => array(
      'name'      => '8.0-alpha12',
      'timestamp' => 1401271007,
    ),
    '8.0-alpha13' => array(
      'name'      => '8.0-alpha13',
      'timestamp' => 1404219557,
    ),
    '8.0.0-alpha14' => array(
      'name'      => '8.0.0-alpha14',
      'timestamp' => 1407318616,
    ),
    '8.0.0-alpha15' => array(
      'name'      => '8.0.0-alpha15',
      'timestamp' => 1411120147,
    ),
    '8.0.0-beta1' => array(
      'name'      => '8.0.0-beta1',
      'timestamp' => 1412143805,
    ),
    '8.0.0-beta2' => array(
      'name'      => '8.0.0-beta2',
      'timestamp' => 1413391193,
    ),
    '8.0.0-beta3' => array(
      'name'      => '8.0.0-beta3',
      'timestamp' => 1415739808,
    ),
    '8.0.0-beta4' => array(
      'name'      => '8.0.0-beta4',
      'timestamp' => 1418793441,
    ),
    '8.0.0-beta5' => array(
      'name'      => '8.0.0-beta5',
      'timestamp' => 1422395106,
    ),
    '8.0.0-beta6' => array(
      'name'      => '8.0.0-beta6',
      'timestamp' => 1422442526,
    ),
    '8.0.0-beta7' => array(
      'name'      => '8.0.0-beta7',
      'timestamp' => 1424821954,
    ),
    '8.0.0-beta8' => array(
      'name'      => '8.0.0-beta8',
      'timestamp' => 1427241056,
    ),
    '8.0.0-beta9' => array(
      'name'      => '8.0.0-beta9',
      'timestamp' => 1427299993,
    ),
  ),
);
